### ISSUE TITLE
Have the default export test for IPv4 or IPv6

### ISSUE THREAD

**Issue by silverwind** [silverwind/is-cidr#1]
I think that instead of assigning the default export to `isCidrV4`, I'd make more sense to check if the given value is either IPv4 or IPv6, e.g. `isCidrV4(input) || isCidrV6(input)`.

**Comment by iarna** [comment]
That seems like a reasonable default. (But please bump the major if you do that!)

**Comment by flipjs** [comment]
I agree with you @iarna . This is a breaking change so it should be a major bump.

**Comment by silverwind** [comment]
Yes, of course, I will update both `cidr-regex` and `is-cidr` and then release new major versions.
