### ISSUE TITLE
Precompile to ES5 (or CommonJS) before publishing

### ISSUE THREAD

**Issue by haraldme** [silverwind/is-cidr#2]
Hi, I'm trying to use ``is-cidr`` in my create-react-app based project, and ran into the problem described here:

https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

Would it be possible to pre-compile this project (and its non-ES5 dependencies, ``cidr-regex`` and ``ip-regex``) down to ES5/CommonJS before publishing?

Best regards,
Harald

**Comment by silverwind** [comment]
Many modules are published as ES6 and I don't want to intruduce extra work on my side to support legacy environments. Please use a bundler like Webpack or Parcel to compile all your JS to ES5.
