### ISSUE TITLE
Allows invalid cidr values

### ISSUE THREAD

**Issue by redmerten** [silverwind/is-cidr#6]
192.169.1.1/24 is not valid because the last 8 bits must be 0
255.1.0.0/8 is not valid because 24 (32-8) bits must be 0

**Comment by silverwind** [comment]
I disagree. `192.169.1.1/24` is valid and this kind of writing is very common to define a IP address and it's subnet size. The "requirement" for a CIDR to to start with it's first address is outdated, there is no valid reason to have it because the start address can be calculated in all cases.

**Comment by dwu-zingbox** [comment]
The notion of 192.168.1.1/24 has been used to specify an IP address along with the associated subnet. However it is not a valid notion only specify the subnet. We can support such user input but convert it to the standard subnet format.
